version: '3.8'

services:
  # api:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "8000:8000"
  #   env_file: .env
  #   container_name: api
  #   depends_on:
  #     - postgres
  #     - redis
  #   volumes:
  #     - ./backend:/app
  #   command: >
  #     sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  # postgres:
  #   image: postgres:latest
  #   container_name: db_app
  #   environment:
  #     POSTGRES_USER: ${DB_USER}  
  #     POSTGRES_PASSWORD: ${DB_PASS}  
  #     POSTGRES_DB: ${DB_NAME}  
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - /db-data:/var/lib/postgresql/

  # redis:
  #   image: redis:latest
  #   container_name: redis_app
  #   ports:
  #     - "6379:6379"
  
  frontend:
    build: ./frontend
    expose: [ 3000 ]
    restart: unless-stopped
    init: true
    env_file:
      - ./frontend/.env
    ports:
      - 443:443
      - 80:80
    volumes:
      - caddy_data:/data
      - caddy_config:/config
  
volumes:
  caddy_data:
  caddy_config:
  static:


